### ISSUE TITLE
Error while compiling (WITHOUT ANY CHANGES TO SOURCE CODE)

### ISSUE THREAD

**Issue by Twingamerdudes** [RaphMar2021/SipaaKernelV4#1]
For some reason, when I try to compile, an error appears about my cosmos version being wrong. Btw, I am on the most recent version of cosmos, and I have compiled it from its source code.
![image](https://user-images.githubusercontent.com/81382687/201371823-5526fd07-c6ea-4816-a0da-3b863ddd8bc4.png)
If anyone could help, it would be appreciated.

**Comment by GreenSoupDeveloper** [comment]
you are using the devkit or the userkit?

**Comment by GreenSoupDeveloper** [comment]
if you are using the dev kit, you can try making a new project and put the sk files to the new project

**Comment by RaphMar2021** [comment]
You need to upgrade the Cosmos Nuget Packages for the libraries of SipaaKernel

**Comment by RaphMar2021** [comment]
Enable include pre released

**Comment by GreenSoupDeveloper** [comment]
> You need to upgrade the Cosmos Nuget Packages for the libraries of SipaaKernel

ye
